"""Add bookings table

Revision ID: 161fcc254b7c
Revises: c740a8f42490
Create Date: 2026-01-26 17:51:38.071828

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '161fcc254b7c'
down_revision: Union[str, Sequence[str], None] = 'c740a8f42490'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_items_id'), table_name='items')
    op.drop_index(op.f('ix_items_owner_id'), table_name='items')
    op.drop_table('items')
    op.add_column('bookings', sa.Column('client_name', sa.String(length=100), nullable=False))
    op.add_column('bookings', sa.Column('phone', sa.String(length=20), nullable=False))
    op.add_column('bookings', sa.Column('email', sa.String(length=100), nullable=True))
    op.add_column('bookings', sa.Column('appointment_time', sa.DateTime(), nullable=True))
    op.add_column('bookings', sa.Column('is_read', sa.Boolean(), nullable=True))
    op.alter_column('bookings', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.create_index(op.f('ix_bookings_id'), 'bookings', ['id'], unique=False)
    op.drop_column('bookings', 'source_url')
    op.drop_column('bookings', 'contact_info')
    op.drop_column('bookings', 'user_name')
    op.drop_column('bookings', 'budget')
    op.drop_index(op.f('ix_cases_featured_year'), table_name='cases')
    op.drop_index(op.f('ix_cases_year'), table_name='cases')
    op.drop_column('cases', 'duration')
    op.drop_column('cases', 'team_members')
    op.drop_column('cases', 'client')
    op.drop_column('cases', 'related_cases')
    op.drop_column('cases', 'difficulty')
    op.drop_column('cases', 'tags')
    op.drop_column('cases', 'testimonials')
    op.drop_column('cases', 'awards')
    op.drop_column('cases', 'services')
    op.drop_column('products', 'updated_at')
    op.drop_column('products', 'summary')
    op.drop_column('products', 'specs')
    op.drop_column('products', 'order_weight')
    op.drop_column('products', 'highlights')
    op.drop_column('project_nodes', 'remark')
    op.drop_index(op.f('ix_project_login'), table_name='projects')
    op.create_index('ix_project_auth', 'projects', ['project_no', 'access_code'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_project_auth', table_name='projects')
    op.create_index(op.f('ix_project_login'), 'projects', ['project_no', 'access_code'], unique=False)
    op.add_column('project_nodes', sa.Column('remark', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('products', sa.Column('highlights', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'[]'::jsonb"), autoincrement=False, nullable=True))
    op.add_column('products', sa.Column('order_weight', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('products', sa.Column('specs', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'[]'::jsonb"), autoincrement=False, nullable=True))
    op.add_column('products', sa.Column('summary', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('products', sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True))
    op.add_column('cases', sa.Column('services', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'[]'::jsonb"), autoincrement=False, nullable=False))
    op.add_column('cases', sa.Column('awards', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'[]'::jsonb"), autoincrement=False, nullable=False))
    op.add_column('cases', sa.Column('testimonials', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('cases', sa.Column('tags', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'[]'::jsonb"), autoincrement=False, nullable=False))
    op.add_column('cases', sa.Column('difficulty', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('cases', sa.Column('related_cases', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'[]'::jsonb"), autoincrement=False, nullable=False))
    op.add_column('cases', sa.Column('client', sa.VARCHAR(length=200), autoincrement=False, nullable=True))
    op.add_column('cases', sa.Column('team_members', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'[]'::jsonb"), autoincrement=False, nullable=False))
    op.add_column('cases', sa.Column('duration', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
    op.create_index(op.f('ix_cases_year'), 'cases', ['year'], unique=False)
    op.create_index(op.f('ix_cases_featured_year'), 'cases', ['featured', 'year'], unique=False)
    op.add_column('bookings', sa.Column('budget', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('bookings', sa.Column('user_name', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('bookings', sa.Column('contact_info', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('bookings', sa.Column('source_url', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_bookings_id'), table_name='bookings')
    op.alter_column('bookings', 'created_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.drop_column('bookings', 'is_read')
    op.drop_column('bookings', 'appointment_time')
    op.drop_column('bookings', 'email')
    op.drop_column('bookings', 'phone')
    op.drop_column('bookings', 'client_name')
    op.create_table('items',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('price', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('category', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('tags', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('status', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('owner_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('items_pkey'))
    )
    op.create_index(op.f('ix_items_owner_id'), 'items', ['owner_id'], unique=False)
    op.create_index(op.f('ix_items_id'), 'items', ['id'], unique=False)
    # ### end Alembic commands ###
