"""Add bookings table

Revision ID: 41a7089fd09c
Revises: 161fcc254b7c
Create Date: 2026-01-26 18:43:44.054959

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '41a7089fd09c'
down_revision: Union[str, Sequence[str], None] = '161fcc254b7c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bookings', sa.Column('user_name', sa.String(length=100), nullable=False))
    op.add_column('bookings', sa.Column('contact_info', sa.String(length=100), nullable=False))
    op.add_column('bookings', sa.Column('budget', sa.String(length=100), nullable=True))
    op.add_column('bookings', sa.Column('source_url', sa.String(length=255), nullable=True))
    op.drop_column('bookings', 'client_name')
    op.drop_column('bookings', 'email')
    op.drop_column('bookings', 'appointment_time')
    op.drop_column('bookings', 'phone')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bookings', sa.Column('phone', sa.VARCHAR(length=20), autoincrement=False, nullable=False))
    op.add_column('bookings', sa.Column('appointment_time', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.add_column('bookings', sa.Column('email', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.add_column('bookings', sa.Column('client_name', sa.VARCHAR(length=100), autoincrement=False, nullable=False))
    op.drop_column('bookings', 'source_url')
    op.drop_column('bookings', 'budget')
    op.drop_column('bookings', 'contact_info')
    op.drop_column('bookings', 'user_name')
    # ### end Alembic commands ###
