"""add_node_id_to_logs

Revision ID: 4d8ed9d5fdf1
Revises: d919797d4fc7
Create Date: 2026-01-28 11:35:19.755007

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '4d8ed9d5fdf1'
down_revision: Union[str, Sequence[str], None] = 'd919797d4fc7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('project_logs', sa.Column('images', postgresql.JSONB(astext_type=sa.Text()), server_default='[]', nullable=True))
    op.drop_index(op.f('ix_project_auth'), table_name='projects')
    op.drop_column('projects', 'manager_name')
    op.drop_column('projects', 'manager_phone')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('projects', sa.Column('manager_phone', sa.VARCHAR(length=20), autoincrement=False, nullable=True))
    op.add_column('projects', sa.Column('manager_name', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.create_index(op.f('ix_project_auth'), 'projects', ['project_no', 'access_code'], unique=False)
    op.drop_column('project_logs', 'images')
    # ### end Alembic commands ###
