"""add_product_fields

Revision ID: d919797d4fc7
Revises: 41a7089fd09c
Create Date: 2026-01-27 18:09:16.177169

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'd919797d4fc7'
down_revision: Union[str, Sequence[str], None] = '41a7089fd09c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('summary', sa.Text(), nullable=True))
    op.add_column('products', sa.Column('specs', postgresql.JSONB(astext_type=sa.Text()), server_default='[]', nullable=True))
    op.add_column('products', sa.Column('highlights', postgresql.JSONB(astext_type=sa.Text()), server_default='[]', nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('products', 'highlights')
    op.drop_column('products', 'specs')
    op.drop_column('products', 'summary')
    # ### end Alembic commands ###
